### ISSUE TITLE
Decide project folder and naming convention

### ISSUE THREAD

**Issue by GZeng3** [kevinchtsang/HEIN11057-2022-23#2]
Repository should have consistent and clear project folder structure and naming of folders and files.

In addition, variables names in the code and column names should also be standardised.

I propose snake_case naming for all folders, files, code variables and table columns.

**Comment by GZeng3** [comment]
Working on this

**Comment by B202395** [comment]
Test

**Comment by GZeng3** [comment]
Folder naming and code variable naming guidelines updating the in Readme.

**Comment by kevinchtsang** [comment]
This work has been completed
